// Static assets for the console.
//
// Two sources, same shape — a map from URL path to a file path readable with
// Bun.file():
//
//   • embedded — `bun run build` runs scripts/gen-ui-assets.ts, which writes
//     src/ui-assets.gen.ts (gitignored) importing every ui/dist file
//     `with { type: "file" }`; `bun build --compile` embeds those into the
//     binary and the import yields /$bunfs/… paths at runtime.
//   • disk — running from a source checkout without the generated module
//     (plain `bun run dev`), serve ui/dist directly if it has been built.
//
// Lookups go through the map only — request paths are never joined onto the
// filesystem, so traversal is impossible by construction.

import { createHash } from "node:crypto";
import { readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export interface UiManifest {
  /** sha256 over the sorted "<path> <sha256(bytes)>" listing of every file. */
  hash: string;
  files: number;
  bytes: number;
}

export interface UiAssets {
  mode: "embedded" | "disk";
  /** URL path ("/index.html", "/assets/index-abc.js") → Bun.file()-able path. */
  files: Record<string, string>;
  /** CSP sha256- source tokens for index.html's inline scripts, so script-src
   *  needs no 'unsafe-inline'. Empty when the shell carries none. */
  inlineScriptHashes: string[];
  /** Identity of exactly the bytes this process will serve — logged at start so
   *  a running console can be matched against a release without trusting the
   *  version string it does not disclose. */
  manifest: UiManifest;
}

/** Pure: extract inline <script> bodies from HTML → CSP hash tokens. */
export function inlineScriptHashesOf(html: string): string[] {
  const out: string[] = [];
  const re = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const body = m[1] ?? "";
    if (!body.trim()) continue;
    out.push(`'sha256-${createHash("sha256").update(body).digest("base64")}'`);
  }
  return out;
}

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
};

export function contentTypeFor(urlPath: string): string {
  const dot = urlPath.lastIndexOf(".");
  const ext = dot >= 0 ? urlPath.slice(dot).toLowerCase() : "";
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

/** Recursively list files under a dist dir as URL-path → absolute-path. */
export function mapDistDir(distDir: string): Record<string, string> {
  const files: Record<string, string> = {};
  const stack = [distDir];
  while (stack.length > 0) {
    const dir = stack.pop() as string;
    // dir descends from the compile-time ui/dist root, never from request input.
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(abs);
      } else if (entry.isFile()) {
        const rel = abs.slice(distDir.length).replaceAll("\\", "/");
        files[rel.startsWith("/") ? rel : `/${rel}`] = abs;
      }
    }
  }
  return files;
}

/**
 * Hash the served bytes. Computed over CONTENT, not over the build that
 * produced it, so two independent builds of the same sources agree and a
 * rebuild comparison is a real check rather than a timestamp diff.
 */
export async function manifestOf(files: Record<string, string>): Promise<UiManifest> {
  const listing = createHash("sha256");
  let bytes = 0;
  for (const urlPath of Object.keys(files).sort()) {
    const buf = await Bun.file(files[urlPath] as string).bytes();
    bytes += buf.length;
    listing.update(`${urlPath} ${createHash("sha256").update(buf).digest("hex")}\n`);
  }
  return { hash: listing.digest("hex"), files: Object.keys(files).length, bytes };
}

/**
 * Resolve the console assets, embedded first, disk fallback. Returns null when
 * neither exists (a source checkout with no built ui/) — callers print the
 * remedy and exit rather than serving an empty shell.
 */
export async function loadUiAssets(): Promise<UiAssets | null> {
  const resolve = async (
    mode: UiAssets["mode"],
    files: Record<string, string>,
  ): Promise<UiAssets> => {
    let inlineScriptHashes: string[] = [];
    try {
      const index = files["/index.html"];
      if (index) inlineScriptHashes = inlineScriptHashesOf(await Bun.file(index).text());
    } catch {
      // hash-less CSP still blocks inline scripts — fail closed, not open
    }
    return { mode, files, inlineScriptHashes, manifest: await manifestOf(files) };
  };
  try {
    // Generated by scripts/gen-ui-assets.ts; absent in a fresh checkout. The
    // literal specifier keeps the bundler embedding it when it exists at
    // compile time; the runtime catch covers dev checkouts where it doesn't.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore -- src/ui-assets.gen.ts is generated at build time
    const gen = (await import("../ui-assets.gen.js")) as {
      UI_ASSETS: Record<string, string>;
    };
    if (Object.keys(gen.UI_ASSETS).length > 0) {
      return await resolve("embedded", gen.UI_ASSETS);
    }
  } catch {
    // fall through to disk mode
  }
  try {
    const distDir = fileURLToPath(new URL("../../ui/dist", import.meta.url));
    const files = mapDistDir(distDir);
    if (files["/index.html"]) return await resolve("disk", files);
  } catch {
    // no built ui on disk either
  }
  return null;
}
