// Generates src/ui-assets.gen.ts (gitignored) from ui/dist: one
// `with { type: "file" }` import per built file, so `bun build --compile`
// embeds the whole console into the single hx-fortress binary. Runs as part of
// `bun run build`, after the ui build; fails loudly when ui/dist is missing so a
// binary can never silently ship without its console.
//
// `--print-hash` writes nothing and prints only the manifest hash of ui/dist.
// CI builds the ui twice and compares the two: the embedded assets are then
// provably the ones this commit's sources produce, not a stale dist that
// happened to be lying in the tree.

import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { manifestOf } from "../src/ui/assets";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(repoRoot, "ui", "dist");
const outFile = join(repoRoot, "src", "ui-assets.gen.ts");
const printHashOnly = process.argv.includes("--print-hash");

if (!existsSync(join(distDir, "index.html"))) {
  console.error("gen-ui-assets: ui/dist/index.html not found — run `bun run build:ui` first.");
  process.exit(1);
}

const files: string[] = [];
const stack = [distDir];
while (stack.length > 0) {
  const dir = stack.pop() as string;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) stack.push(abs);
    else if (entry.isFile()) files.push(abs);
  }
}
files.sort();

const byUrlPath: Record<string, string> = {};
for (const abs of files) {
  const rel = abs.slice(distDir.length).replaceAll("\\", "/");
  byUrlPath[rel.startsWith("/") ? rel : `/${rel}`] = abs;
}
const manifest = await manifestOf(byUrlPath);

if (printHashOnly) {
  console.log(manifest.hash);
  process.exit(0);
}

const lines: string[] = [
  "// AUTO-GENERATED by scripts/gen-ui-assets.ts — do not edit, do not commit.",
  "// Maps URL paths to embedded ui/dist files (see src/ui/assets.ts).",
  '// @ts-nocheck — tsc has no model for `with { type: "file" }` import',
  "// attributes (it sees HTMLBundle/any); at runtime each import is a path",
  "// string, embedded into the binary by `bun build --compile`.",
  "",
];
const entries: string[] = [];
Object.keys(byUrlPath).forEach((urlPath, i) => {
  lines.push(`import f${i} from "../ui/dist${urlPath}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: f${i},`);
});
lines.push("", "export const UI_ASSETS: Record<string, string> = {", ...entries, "};", "");

writeFileSync(outFile, lines.join("\n"));
console.log(
  `gen-ui-assets: embedded ${files.length} files from ui/dist (sha256 ${manifest.hash})`,
);
