import React, { useRef, useState } from "react";
import { useApp } from "../state";
import { egressHtml, trailHtml, buildReport } from "../render";
import { fmtInt, TOTAL_SESSIONS } from "../data";
import { copyText, downloadBlob, flashPanel } from "../lib/util";
import { reportPdfBytes } from "../lib/pdf";

export default function Compliance() {
  const app = useApp();
  const [report, setReport] = useState("");
  const retentionRef = useRef<HTMLDivElement>(null);
  const audittrailRef = useRef<HTMLDivElement>(null);
  const total = fmtInt(TOTAL_SESSIONS);

  const showReport = () => {
    const r = buildReport();
    setReport(r);
    return r;
  };
  const onGenerate = (e: React.MouseEvent<HTMLButtonElement>) => {
    const r = showReport();
    copyText(r, e.currentTarget, "Copied to clipboard");
    const t = app.trail[0];
    if (!t || t[2] !== "Exported the compliance report" || t[0] !== "Just now") app.addTrail("Exported the compliance report", "one-page posture summary, copied from this console");
  };
  const onPdf = () => {
    const r = showReport();
    downloadBlob(reportPdfBytes(r), "application/pdf", "hx-fortress-compliance-summary.pdf");
    const t = app.trail[0];
    if (!t || t[2] !== "Downloaded the compliance report as PDF" || t[0] !== "Just now") app.addTrail("Downloaded the compliance report as PDF", "hx-fortress-compliance-summary.pdf · generated by this console");
  };

  return (
    <section className={app.view === "compliance" ? "view active" : "view"} id="view-compliance">
      <div className="kicker">Compliance</div>
      <h1>Posture, Egress &amp; Audit</h1>
      <p className="lede">The corporate lenses on this fortress: where data can leave, how long it's kept, and who did what in this console. Built for the person who has to answer for it.</p>

      <div className="tiles" style={{ gridTemplateColumns: "repeat(4,1fr)" }}>
        <div className="tile" onClick={() => app.goto("residency")}>
          <div className="thead"><span className="tdot"></span> Residency</div>
          <div className="tstate">Verified</div>
          <div className="tsub" id="postResSub">{total} of {total} · nightly audit</div>
        </div>
        <div className="tile" onClick={() => flashPanel(document.getElementById("egressPanel"))}>
          <div className="thead"><span className="tdot"></span> Egress</div>
          <div className="tstate">Inventoried</div>
          <div className="tsub">4 documented paths · nothing else</div>
        </div>
        <div className="tile" onClick={() => flashPanel(retentionRef.current)}>
          <div className="thead"><span className="tdot"></span> Retention</div>
          <div className="tstate">Indefinite</div>
          <div className="tsub">bucket versioning on · no expiry rule</div>
        </div>
        <div className="tile" onClick={() => flashPanel(audittrailRef.current)}>
          <div className="thead"><span className="tdot"></span> Admin audit</div>
          <div className="tstate">Logged</div>
          <div className="tsub">every console action · 180-day trail</div>
        </div>
      </div>

      <div className="panel" id="egressPanel">
        <h2>Egress Inventory</h2>
        <div className="h2sub">Every way bytes can leave this host — the complete list. Anything not here does not happen.</div>
        <div className="rowlist ops" id="egressList" dangerouslySetInnerHTML={{ __html: egressHtml() }} />
      </div>

      <div className="panel" id="retentionPanel" ref={retentionRef}>
        <h2>Retention</h2>
        <div className="facts wide">
          <div className="frw"><span className="k">Transcripts (bucket)</span><span><span className="v">Kept indefinitely</span><div className="vs">no lifecycle expiry configured on <span className="mono">orange-corp-hx-fortress</span> — retention is governed by the org's own bucket policy, nothing else</div></span></div>
          <div className="frw"><span className="k">Bucket versioning</span><span><span className="v">On</span><div className="vs">overwrites and deletes keep a recoverable prior version</div></span></div>
          <div className="frw"><span className="k">Metadata (Postgres)</span><span><span className="v">Kept with the transcript</span><div className="vs">rows mirror the bucket — removing a session removes both</div></span></div>
          <div className="frw"><span className="k">Fortress logs</span><span><span className="v">90 days on disk</span><div className="vs"><span className="mono">~/.let/hx-fortress/logs/fortress.jsonl</span> · rotated by the service</div></span></div>
          <div className="frw"><span className="k">Audit trail</span><span><span className="v">180 days</span><div className="vs">console actions and residency audits, exportable below</div></span></div>
        </div>
      </div>

      <div className="panel" id="audittrailPanel" ref={audittrailRef}>
        <h2>Admin Audit Trail</h2>
        <div className="h2sub">Every state-changing action taken in this console, newest first. Read-only views are not logged.</div>
        <div className="rowlist ops" id="trailList" dangerouslySetInnerHTML={{ __html: trailHtml(app.trail) }} />
      </div>

      <div className="panel">
        <h2>Compliance Report</h2>
        <div className="setrow" style={{ borderBottom: "none", paddingBottom: 6 }}>
          <div className="txt"><b>One-page posture summary</b><p>Residency, egress, retention and adoption in a single copyable block — the answer to “where does our AI session data live?” for auditors and security reviews.</p></div>
          <span style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <button className="iconbtn" id="reportPdfBtn" title="Download as PDF" style={{ width: 36, height: 36 }} onClick={onPdf}>
              <svg className="ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" /><path d="M14 3v5h5M12 11v6M9.5 14.5L12 17l2.5-2.5" /></svg>
            </button>
            <button className="btn" id="reportBtn" onClick={onGenerate}>Generate report</button>
          </span>
        </div>
        <div className={report ? "proof paper on" : "proof paper"} id="reportOut">{report}</div>
      </div>
    </section>
  );
}
